const appname = "ApexShop";
const appversion = "Version 1.0.0";
const credits = "@ApexDigital";
const email = "Email";
const emailHint = "admin@admin.com";
const password = "Password";
const passwordHint = "******";
const forgetPass = "Forget Password?";
const login = "Log in";
const signup = "Sign up";
const createNewAccount = "or , create a new account";
const loginWith = "Log in with";
const reTypePassword = "Retype Password";
const name = "Name";
const nameHint = "Hasan Diab";
const privacyPolicy = "Privacy Policy";
const termAndCond = "Terms and Conditions";
const alreadyHavingAccount = "Already have an account? ";
const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";
const serachAnyThing = "Search anything...",
    todayDeal = "Today's Deal",
    flashSale = "Flash sale",
    topSeller = "Top Seller",
    brand = "Brand",
    womenDress = "Women Dress",
    girlSwatch = "Girls Watches",
    mobilePhone = "Mobile Phone",
    boysGlasses = "Boys Glasses",
    tShirts = "Tshirts",
    girlDress = "Girl Dress",
    topCategories = "Top Categories",
    featuredProudcts = "Featured Proudcts ",
    featuredCategories = "Featured Categories ";
